apiVersion: v1
kind: Service
metadata:
  name: banana-service
  labels:
    app: banana-app
spec:
  selector:
    app: banana-app
    version: banana
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30000